# Generated by Django 4.0.3 on 2022-04-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_ticket_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='hallseat',
            options={'verbose_name': 'HeallSeat', 'verbose_name_plural': 'HallSeats'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='seat',
            options={'verbose_name': 'Seat', 'verbose_name_plural': 'Seats'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='favorites',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hall',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hallseat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='movie',
            table=None,
        ),
        migrations.AlterModelTable(
            name='seat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='session',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
