# Generated by Django 4.0.3 on 2022-04-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='original_language',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='original_title',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.genres'),
        ),
    ]
