# Generated by Django 4.0.3 on 2022-05-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_booking_is_paied_remove_session_hall_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='datetime',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
