# Generated by Django 4.0.3 on 2022-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(max_length=150, null=True),
        ),
    ]
