# Generated by Django 4.0.3 on 2022-05-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_session_datetime_session_date_session_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hall',
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.hall'),
            preserve_default=False,
        ),
    ]
