# Generated by Django 4.0.3 on 2022-05-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_booking_hall_session_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
