# Generated by Django 4.0.3 on 2022-04-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_movie_release_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
