# Generated by Django 4.0.3 on 2022-04-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
