# Generated by Django 4.0.3 on 2022-05-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_comment_date_remove_comment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_guest_came',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
